### ISSUE TITLE
feelinglucky broken (affects !mdn and !g)

### ISSUE THREAD

**Issue by brigand** [oftn/oftn-bot#55]
Here's the error:

```
TypeError: Cannot read property 'results' of null
    at IncomingMessage.<anonymous> (/home/node/lib/feelinglucky/index.js:19:44)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by brigand** [comment]
Here's the error:

> {"responseData": null, "responseDetails": "The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)", "responseStatus": 403}

**Comment by eligrey** [comment]
https://news.ycombinator.com/item?id=11625633 :frowning: 

We either need to reverse engineer the google.com internal JS API (used by <https://www.google.com/#q=test>) or resort to scraping HTML.

**Comment by brigand** [comment]
Maybe useful https://support.google.com/customsearch/answer/2631040?hl=en

**Comment by eligrey** [comment]
I don't think that provides a JSON API though, so we may still need to scrape that to extract the relevant content.

**Comment by yorickvP** [comment]
I read some API docs, they have a JSON API

**Comment by yorickvP** [comment]
MDN could maybe be fixed using https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Search

**Comment by hagb4rd** [comment]
Feeling Ducky! 
:grin: 

Created a replacement. Works the same Googles Lucky Search used to. 

Greetz!

[Pull Request](https://github.com/oftn-oswg/oftn-bot/pull/60) here:

 #60
